### ISSUE TITLE
Custom message/description settings

### ISSUE THREAD

**Issue by DimonYoing** [Kygekraqmak/KygekEasyGamemode#2]
Add the ability to translate each mode, that is, if "Survival" "Creative" "Adventure" "Spectaror" is written so that these inscriptions can be changed to your own or another language

**Comment by DimonYoing** [comment]
Because the language of the mode inscription is indicated only in English, and I need in another language the inscription of the message about the mode

**Comment by KygekDev** [comment]
@DimonYoing see PR #3 and let me know there if you have any feedbacks!

**Comment by tobydev27** [comment]
Done by https://github.com/thebigcrafter/KygekEasyGamemode/commit/9178aaf6791f0218a281467756dfa3aec068bd4a
